version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=play_console_importer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ./BACKEND
    command: sh -c "python manage.py wait_for_db && python manage.py migrate && gunicorn play_reports.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./BACKEND:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build: ./FRONTEND
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: