# Generated by Django 5.2.1 on 2025-08-10 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invited_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_received', to='play_reports.client', verbose_name='Client Invité'),
        ),
        migrations.AlterField(
            model_name='client',
            name='role_client',
            field=models.CharField(choices=[('Owner', 'Owner'), ('MEMBRE_INVITE', 'Membre Invité')], default='Owner', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
