# Generated by Django 5.1.5 on 2025-07-10 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_reports', '0002_alter_cancellationreasons_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la source')),
                ('bucket_uri', models.URLField(max_length=500, verbose_name='URI du bucket')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Succès'), ('error', 'Erreur'), ('warning', 'Avertissement')], default='pending', max_length=20, verbose_name='Statut')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Dernière synchronisation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Métadonnées')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='play_reports.tenant')),
            ],
            options={
                'verbose_name': 'Source de données',
                'verbose_name_plural': 'Sources de données',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'bucket_uri')},
            },
        ),
        migrations.CreateModel(
            name='DataSourceSyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'En cours'), ('success', 'Succès'), ('error', 'Erreur'), ('warning', 'Avertissement')], max_length=20, verbose_name='Statut')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Début')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('log_message', models.TextField(blank=True, null=True, verbose_name='Message de journal')),
                ('records_processed', models.PositiveIntegerField(default=0, verbose_name='Enregistrements traités')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_histories', to='play_reports.datasource', verbose_name='Source de données')),
            ],
            options={
                'verbose_name': 'Historique de synchronisation',
                'verbose_name_plural': 'Historiques de synchronisation',
                'db_table': 'data_source_sync_history',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FileTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(verbose_name='ID du locataire')),
                ('file_path', models.TextField(verbose_name='Chemin du fichier')),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Empreinte du fichier')),
                ('report_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type de rapport')),
                ('target_table', models.CharField(blank=True, max_length=255, null=True, verbose_name='Table cible')),
                ('first_processed', models.DateTimeField(auto_now_add=True, verbose_name='Premier traitement')),
                ('last_processed', models.DateTimeField(auto_now=True, verbose_name='Dernier traitement')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
            ],
            options={
                'verbose_name': 'Suivi de fichier',
                'verbose_name_plural': 'Suivis de fichiers',
                'db_table': 'file_tracking',
                'indexes': [models.Index(fields=['tenant_id', 'file_path'], name='file_tracki_tenant__1706ac_idx'), models.Index(fields=['last_processed'], name='file_tracki_last_pr_7af79b_idx')],
                'unique_together': {('tenant_id', 'file_path')},
            },
        ),
    ]
