# Generated by Django 5.2.1 on 2025-08-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_reports', '0002_client_email_invitation_invited_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('INVITED', 'Invité'), ('INACTIVE', 'Inactif')], default='ACTIVE', max_length=20),
        ),
    ]
