# Generated by Django 5.1.5 on 2025-07-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_reports', '0003_datasource_datasourcesynchistory_filetracking'),
        ('play_reports', '0003_datasource_datasourcesynchistory_filetracking_and_more'),
    ]

    operations = [
    ]
