# Generated by Django 5.2.1 on 2025-08-12 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_reports', '0004_alter_client_first_name_alter_client_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
